### PR TITLE
Merge tag Homebrew/1.2.4 into Linuxbrew/master

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Four failures from `brew tests`:
```
FFFF......................................
Failures:
  1) Language::Java::overridable_java_home_env returns java_home path with version if version specified
     Failure/Error: expect(java_home[:JAVA_HOME]).to include("--version blah")
       expected nil to include "--version blah", but it does not respond to `include?`
     # ./test/language/java_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:87:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
  2) Language::Java::overridable_java_home_env returns java_home path without version if version is not specified
     Failure/Error: expect(java_home[:JAVA_HOME]).not_to include("--version")
       expected nil not to include "--version", but it does not respond to `include?`
     # ./test/language/java_spec.rb:24:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:87:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
  3) Language::Java::java_home_env returns java_home path without version if version is not specified
     Failure/Error: expect(java_home[:JAVA_HOME]).not_to include("--version")
       expected nil not to include "--version", but it does not respond to `include?`
     # ./test/language/java_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:87:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
  4) Language::Java::java_home_env returns java_home path with version if version specified
     Failure/Error: expect(java_home[:JAVA_HOME]).to include("--version blah")
       expected nil to include "--version blah", but it does not respond to `include?`
     # ./test/language/java_spec.rb:7:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:87:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
Finished in 4.27 seconds (files took 7.3 seconds to load)
42 examples, 4 failures
Failed examples:
rspec ./test/language/java_spec.rb:17 # Language::Java::overridable_java_home_env returns java_home path with version if version specified
rspec ./test/language/java_spec.rb:22 # Language::Java::overridable_java_home_env returns java_home path without version if version is not specified
rspec ./test/language/java_spec.rb:10 # Language::Java::java_home_env returns java_home path without version if version is not specified
rspec ./test/language/java_spec.rb:5 # Language::Java::java_home_env returns java_home path with version if version specified
```
https://travis-ci.org/Linuxbrew/brew/jobs/250841197#L541-L544

**Comment by sjackman** [comment]
You can run just these failed tests locally using…
```ruby
brew tests --only=language/java
```

**Comment by iMichka** [comment]
This passes on my mac. So I'll need to test this on my Linux box when I am home. My flight is slightly delayed so I do not know if I will be able to have a look at this today. I'll have time to debug this on Friday evening only.

**Comment by sjackman** [comment]
It can wait until Friday. On my Mac I use `Docker.app` to pull the `linuxbrew/linuxbrew` image to work on Linuxbrew. (mostly in the airport, interestingly enough)
See https://www.docker.com/docker-mac

**Comment by sjackman** [comment]
CI passed!

**Comment by sjackman** [comment]
I'm okay with the `test/language/java` fix for now. https://github.com/Linuxbrew/brew/pull/424/commits/269be25411af00b5ecf9764a92c8061dc79ed8ca
A possible long-term solution would be to implement a shell script compatible with `/usr/libexec/java_home` of macOS for Linuxbrew.

**Review by sjackman — APPROVED** [review]
Thanks, Michka!

**Pull request merged**
