### PR TITLE
Fix uuidgen for Windows Subsystem for Linux

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
@netpyoung Please test this PR if you can.

**Comment by netpyoung** [comment]
@sjackman It's works. without warning message.

**Comment by sjackman** [comment]
@netpyoung Great! Glad to hear it. Can you please report the output of

``` sh
which -a uuidgen
```

**Comment by sjackman** [comment]
Merged. Thanks for the bug report, @netpyoung!

**Comment by netpyoung** [comment]
@sjackman thanks you :+1: 

```
pyoung@DESKTOP-UNNNKLB:~/.linuxbrew$ which -a uuidgen
/usr/bin/uuidgen
pyoung@DESKTOP-UNNNKLB:~/.linuxbrew$ cat /proc/sys/kernel/ostype
Linux
pyoung@DESKTOP-UNNNKLB:~/.linuxbrew$ cat /proc/sys/kernel/osrelease
3.4.0-Microsoft
```

**Pull request closed without merging**
