### PR TITLE
brew.sh: do not hardcode path to awk

### PR DESCRIPTION
**Pull request by glensc**
refs #416

no all systems have awk at `/usr/bin`, mine has at `/bin`

### CODE REVIEW

**Comment by glensc** [comment]
btw, why the modified file lacks hashbang? should be `/bin/sh` or `/bin/bash` depending whether bash specific syntax is used.

**Comment by sjackman** [comment]
Where is `awk` on your system? Please report `which -a awk`

**Comment by sjackman** [comment]
> btw, why the modified file lacks hashbang? should be /bin/sh or /bin/bash depending whether bash specific syntax is used.

This file is not meant to be executed directly, but is instead sourced by `bin/brew`. Its syntax is `/bin/bash`.

**Comment by sjackman** [comment]
TravisCI failure on macOS is unrelated to this PR.

**Comment by sjackman** [comment]
Where is `awk` on your system? Please report `which -a awk`

**Comment by glensc** [comment]
@sjackman it's described in PR description:

> no all systems have awk at /usr/bin, mine has at /bin

**Comment by sjackman** [comment]
Which distribution of Linux are you using?

**Comment by glensc** [comment]
https://www.pld-linux.org/

but what does it really matter? you kind of already [accepted](https://github.com/Linuxbrew/brew/issues/416#issuecomment-311698487) such change...

**Comment by sjackman** [comment]
It helps me to understand your motivation for this PR, and which other users may be affected by this issue.

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Linuxbrew, Elan! :tada:

**Pull request merged**
