### PR TITLE
make: remove make shim

### PR DESCRIPTION
**Pull request by iMichka**
This breaks multiple formulae:

```
ntl: fatal error: gmp.h: No such file or directory
gnutls: fatal error: gmp.h: No such file or directory
util-linux: ncursesw/term.h: No such file or directory
tig: fatal error: ncursesw/curses.h
imagemagik@6: fatal error: bzlib.h: No such file or directory
htslib: fatal error: zlib.h: No such file or directory
pspg: fatal error: ncurses.h: No such file or directory
gsoap: fatal error: openssl/bio.h: No such file or directory
```

This is a new addition to brew which breaks too many things. I propose to merge this, tag and release 1.7.1, proceed with bottle building. This leaves us more time to fix the make shim or to investigate the failure.

### CODE REVIEW

**Comment by jonchang** [comment]
* The make shim is a red herring, removing it shouldn't affect anything.
* Commit 6ad6128f9b280ccbf1d5382744a50c8aa6dccff8 from a month ago added the make shim and also updated `$HOMEBREW_CCCFG` to enable superenv `refurbish_args` for make-based builds, so why is this issue only just appearing now??
    * I'm wondering if `refurbish_args` is *also* a red herring.
* without a test case I can reproduce locally I'm not sure I can debug this. `brew install tig` works a-ok for me excepting the case when `ncurses` is unlinked.

**Comment by iMichka** [comment]
> why is this issue only just appearing now??

Regarding this, I may have an explanation. There were a bunch of short releases + 1.7.0. All this tool time to get merged and tagged. Due to the bottle upload problem, I had not much time to test building of bottles. So for most of the users it was not a problem. We have around 10 days of bottle building of backlog.

**Comment by iMichka** [comment]
With the make shim, no make.cc file is generated, so I have no clue what superenv is trying to do here.
Removing the make shim also brings back the make.cc log file. Though it may just be a side effect.

**Comment by iMichka** [comment]
I merged this so I can proceed with bottle building. This leaves us a little bit of time to find a better solution and to properly debug this.

**Comment by xu-cheng** [comment]
I think the problem may come from `pathremove "$HOMEBREW_LIBRARY/Homebrew/shims/linux/super"` in the original make shim. 

I understand it is there to prevent fork-bomb. However, by removing the superenv path, it also disables superenv completely. i.e. the superenv cc is no longer picked up.

The correct approach would be something similar to the git shim. Find the path to the real make binary, then execute it.  Or we could do:
```
OLD_PATH="$PATH"
pathremove "$HOMEBREW_LIBRARY/Homebrew/shims/linux/super"
MAKE="$(which "$MAKE")"
export PATH="$OLD_PATH"
exec "$MAKE" "$@"
```

Just my 2 cents. I hope it may be helpful. 😉

**Comment by maxim-belkin** [comment]
Thanks, @xu-cheng! This is it!

**Pull request closed without merging**
