### PR TITLE
Merge tag Homebrew/1.2.3 into Linuxbrew/master

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
@sjackman I fixed the style errors.

I think that some should be fixed upstream, there may be a mismatch in ruby version/style checks, and we have a more recent version, so we have more errors.

I did not fix the following one:
```
Library/Homebrew/dev-cmd/audit.rb:876:3: C: Assignment Branch Condition size for line_problems is too high. [253.4/250]
  def line_problems(line, _lineno)
  ^^^
```

I think that one should be fixed upstream.

**Comment by sjackman** [comment]
@iMichka You can fix that last style issue by editing `.rubocop.yml` and increasing `Metrics/MethodLength` to 254:
https://github.com/Linuxbrew/brew/blob/master/Library/.rubocop.yml#L74-L75
The CI runs of the formula taps will fail unless `brew style` and `brew tests` succeed.

**Comment by iMichka** [comment]
The cop to change was Metrics/AbcSize. Lets see if this helps.

**Comment by sjackman** [comment]
Woops, yep, sorry, I meant `AbcSize`.

**Review by sjackman — APPROVED** [review]

**Pull request merged**
