### PR TITLE
Merge 1.6.16

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Review by jonchang — APPROVED** [review]
I don't see anything that would cause issues, assuming tests pass.

**Comment by iMichka** [comment]
This one looks quite safe :)

**Comment by iMichka** [comment]
Interestingly the build after the merge failed ...

```


Failures:



  1) Hbc::CLI::Install returns multiple suggestions for a Cask fragment

     Failure/Error:

       expect {

         described_class.run("local")

       }.to raise_error(Hbc::CaskUnavailableError, /Cask 'local' is unavailable: No Cask with this name exists\. Did you mean one of these\?\nlocal-caffeine\nlocal-transmission/)



       expected Hbc::CaskUnavailableError with message matching /Cask 'local' is unavailable: No Cask with this name exists\. Did you mean one of these\?\nlocal-caffeine\nlocal-transmission/, got #<Hbc::CaskUnavailableError: Cask '0-ad' is unavailable: '/tmp/homebrew-tests-20180718-6557-1j2lcdd/prefix/Library/Taps/homebrew/homebrew-cask/Casks/0-ad.rb' does not exist.> with backtrace:

         # ./cask/lib/hbc/cask_loader.rb:51:in `load'

         # ./cask/lib/hbc/cask.rb:20:in `block in each'

         # ./cask/lib/hbc/cask.rb:19:in `each'

         # ./cask/lib/hbc/cask.rb:19:in `each'

         # ./searchable.rb:26:in `select'

         # ./searchable.rb:26:in `search_string'

         # ./searchable.rb:7:in `search'

         # ./extend/os/mac/search.rb:29:in `search_casks'

         # ./cask/lib/hbc/cli/abstract_command.rb:55:in `suggestion_message'

         # ./cask/lib/hbc/cli/abstract_command.rb:50:in `rescue in casks'

         # ./cask/lib/hbc/cli/abstract_command.rb:45:in `casks'

         # ./cask/lib/hbc/cli/install.rb:14:in `run'

         # ./cask/lib/hbc/cli/abstract_command.rb:33:in `run'

         # ./test/cask/cli/install_spec.rb:76:in `block (3 levels) in <top (required)>'

         # ./test/cask/cli/install_spec.rb:75:in `block (2 levels) in <top (required)>'

         # ./test/support/helper/spec/shared_context/homebrew_cask.rb:38:in `block (2 levels) in <top (required)>'

         # ./test/spec_helper.rb:117:in `block (2 levels) in <top (required)>'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

     # ./test/cask/cli/install_spec.rb:75:in `block (2 levels) in <top (required)>'

     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:38:in `block (2 levels) in <top (required)>'

     # ./test/spec_helper.rb:117:in `block (2 levels) in <top (required)>'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'



  2) Hbc::CLI::Install returns a suggestion for a misspelled Cask

     Failure/Error:

       expect {

         described_class.run("localcaffeine")

       }.to raise_error(Hbc::CaskUnavailableError, /Cask 'localcaffeine' is unavailable: No Cask with this name exists\. Did you mean â€œlocal-caffeineâ€?/)



       expected Hbc::CaskUnavailableError with message matching /Cask 'localcaffeine' is unavailable: No Cask with this name exists\. Did you mean â€œlocal-caffeineâ€?/, got #<Hbc::CaskUnavailableError: Cask '0-ad' is unavailable: '/tmp/homebrew-tests-20180718-6557-1j2lcdd/prefix/Library/Taps/homebrew/homebrew-cask/Casks/0-ad.rb' does not exist.> with backtrace:

         # ./cask/lib/hbc/cask_loader.rb:51:in `load'

         # ./cask/lib/hbc/cask.rb:20:in `block in each'

         # ./cask/lib/hbc/cask.rb:19:in `each'

         # ./cask/lib/hbc/cask.rb:19:in `each'

         # ./searchable.rb:26:in `select'

         # ./searchable.rb:26:in `search_string'

         # ./searchable.rb:7:in `search'

         # ./extend/os/mac/search.rb:29:in `search_casks'

         # ./cask/lib/hbc/cli/abstract_command.rb:55:in `suggestion_message'

         # ./cask/lib/hbc/cli/abstract_command.rb:50:in `rescue in casks'

         # ./cask/lib/hbc/cli/abstract_command.rb:45:in `casks'

         # ./cask/lib/hbc/cli/install.rb:14:in `run'

         # ./cask/lib/hbc/cli/abstract_command.rb:33:in `run'

         # ./test/cask/cli/install_spec.rb:70:in `block (3 levels) in <top (required)>'

         # ./test/cask/cli/install_spec.rb:69:in `block (2 levels) in <top (required)>'

         # ./test/support/helper/spec/shared_context/homebrew_cask.rb:38:in `block (2 levels) in <top (required)>'

         # ./test/spec_helper.rb:117:in `block (2 levels) in <top (required)>'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

         # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

     # ./test/cask/cli/install_spec.rb:69:in `block (2 levels) in <top (required)>'

     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:38:in `block (2 levels) in <top (required)>'

     # ./test/spec_helper.rb:117:in `block (2 levels) in <top (required)>'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'



Finished in 5 minutes 19 seconds (files took 4.51 seconds to load)

1129 examples, 2 failures
```

**Comment by iMichka** [comment]
> expected Hbc::CaskUnavailableError with message matching /Cask 'localcaffeine' is unavailable: No Cask with this name exists\. Did you mean â€œlocal-caffeineâ€�?/, got #<Hbc::CaskUnavailableError: Cask '0-ad' is unavailable: '/tmp/homebrew-tests-20180718-6557-1j2lcdd/prefix/Library/Taps/homebrew/homebrew-cask/Casks/0-ad.rb' does not exist.> with backtrace:

**Pull request merged**
