### PR TITLE
merge-homebrew: Add help text

### PR DESCRIPTION
**Pull request by bw-yuhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
-----

This adds text to `merge-homebrew.rb` such that `brew help merge-homebrew` produces a useful result.

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
@sjackman should I bother running `brew man` on this PR and on #210? That's probably just making more work for ourselves during merges IMO.

**Comment by sjackman** [comment]
If merged in this repo, we'll need to run `brew man` to prevent further CI failures in this repo. Alternatively, we can move these Linuxbrew dev scripts to a different repo. Homebrew has `homebrew/dev-tools`. Either we could fork that, or we could create our own repo. I'm leaning toward the latter, to avoid another forked repo that needs merging. I suggest we call this new repo `linuxbrew/dev`.

**Comment by bw-yuhogg** [comment]
> Either we could fork that, or we could create our own repo. I'm leaning toward the latter, to avoid another forked repo that needs merging. I suggest we call this new repo linuxbrew/dev.

:+1: on the plan.

The name does risk causing some confusion though IMO; mostly with homebrew/dev-tools and to a lesser extent with homebrew/devel-only. Perhaps something involving the word "maintainer"?

On a side note, I've been thinking about merging rwhogg/travis-debug into Linuxbrew too; linuxbrew/dev would be a natural place to put it.

**Comment by sjackman** [comment]
I'm thinking `linuxbrew/developer`. The small distinction is that these scripts are potentially useful to other Linuxbrew developers other than us maintainers with commit rights.

**Comment by bw-yuhogg** [comment]
I'm happy with `linuxbrew/developer`. Probably a line or two of clarification in the README.md or CONTRIBUTING.md files would be sufficient to limit confusion.

**Comment by sjackman** [comment]
I've created https://github.com/Linuxbrew/homebrew-developer (and retained history)!
Merged in https://github.com/Linuxbrew/homebrew-developer/commit/b33700608a2cf244001b7dfbc570f6da81f8c70c

**Pull request closed without merging**
