### PR TITLE
BuildOptions: Do not enable --with-default-names by default [Linux]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
PR https://github.com/Linuxbrew/homebrew-core/pull/8861 must be merged before this PR is merged.

**Comment by jonchang** [comment]
Probably should have rebased from the command line, but I'll do that if CI passes and this is ready to merge.

**Comment by jonchang** [comment]
CI blocked by https://github.com/Linuxbrew/brew/pull/813

**Comment by sjackman** [comment]
Merged.

**Pull request merged**
