### PR TITLE
Adds glibc detection for Solus OS

### PR DESCRIPTION
**Pull request by kenaniah**

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks for the PR, Kenaniah. Any idea why Solus have chosen to put `libc.so.6` in `/usr/lib64` rather than the more common `/lib64`? I'd encourage the Solus developers to follow convention and use `/lib64`.

**Comment by sjackman** [comment]
Does the directory `/lib64` exist? And does it contain the file `/lib64/ld-linux-x86-64.so.2`? But not the file `libc.so.6`?

**Comment by kenaniah** [comment]
On x86_64, `/usr/lib64` is symlinked to `/usr/lib`, but I'll have to re-run the live CD again to answer your other questions. I'll see if I can do that later on today.

**Comment by sjackman** [comment]
Can you please modify your PR to add `/usr/lib64/libc.so.6` immediately after `/lib64/libc.so.6` and `/usr/lib/libc.so.6` after `/lib/libc.so.6`?

**Review by sjackman — CHANGES_REQUESTED** [review]
Can you please modify your PR to add `/usr/lib64/libc.so.6` immediately after `/lib64/libc.so.6` and `/usr/lib/libc.so.6` immediately after `/lib/libc.so.6`?

**Comment by sjackman** [comment]
Unrelated failure on CircleCI but oddly not seen on TravisCI on Linux.
```
Failures:

  1) Bash every `.sh` file has valid bash syntax
     Failure/Error: expect(path).to have_valid_bash_syntax

       expected that /home/ubuntu/brew/Library/Homebrew/cmd/shcmd.sh is a valid Bash file:
       /bin/bash: /home/ubuntu/brew/Library/Homebrew/cmd/shcmd.sh: No such file or directory
     # ./test/bash_spec.rb:29:in `block (4 levels) in <top (required)>'
     # ./test/bash_spec.rb:25:in `each'
     # ./test/bash_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:79:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 3.7 seconds (files took 20.23 seconds to load)
16 examples, 1 failure

Failed examples:

rspec ./test/bash_spec.rb:24 # Bash every `.sh` file has valid bash syntax
```

**Comment by sjackman** [comment]
Merged. Thanks for your contribution to Linuxbrew, Kenaniah!

**Pull request merged**
