### PR TITLE
ENV: pass formula to setup_build_environment

### PR DESCRIPTION
**Pull request by iMichka**
Second attempt to fix the perl postinstall step.

The perl formula will need to be modified and will need to pass `self` to `with_build_environment`.

### CODE REVIEW

**Comment by jonchang** [comment]
I guess I'm a bit lost, there only seems to be one other caller for this function and no callers other than perl.rb in linuxbrew. I guess it's fine but I'm not sure if upstream would be interested in this patch since the perl postinstall step seems like almost a hack.

**Comment by iMichka** [comment]
This is the point. I guess that the we do not want to have superenv enabled during postinstall by default. So you need a way to manually set the env. For Perl we need to compile these modules in the postinstall step (not sure why exactly).

Soni think this here will fix our current problem. If it is what we want in the long run as a solution is a different topic.

**Review by xu-cheng — APPROVED** [review]

**Comment by sjackman** [comment]
We recently enabled `ENV.refurbish_args` by default.
`brew postinstall` does not call `ENV.setup_build_environment`
`perl` calls `ENV.with_build_environment` in `postinstall`
`ENV.with_build_environment` calls `ENV.setup_build_environment(formula = nil)`
`HOMEBREW_FORMULA_PREFIX` is set to `nil`
`shims/super/cc` does not know which formula is being built.
These two lines of code do not work:
https://github.com/Linuxbrew/brew/blob/199540b52f6e33184a061eda8473042a98e0ad03/Library/Homebrew/shims/super/cc#L231-L232

Instead of Perl calling `ENV.with_build_environment`, I propose we instead call…
```ruby
ENV.setup_build_environment(self)
```

**Comment by sjackman** [comment]
Closing without merging. See above comment.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/Linuxbrew/homebrew-core/pull/8842

**Pull request closed without merging**
