### PR TITLE
README.md: Add Shaun and myself as lead maintainers

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
You might want to update the man pages to accomodate these changes too. See https://github.com/Linuxbrew/brew/pull/439 for an example of what sort of changes might be needed.

**Comment by sjackman** [comment]
Try running `brew man --fail-if-changed` locally. Is the output sensible?

**Comment by iMichka** [comment]
Done

**Review by sjackman — APPROVED** [review]
Thanks, Michka!

**Pull request closed without merging**
