### PR TITLE
glibc 2.17 or later is required to pour a bottle [Linux]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Two useful snippets for formulae that require more recents versions of `glibc` and `gcc`:
```ruby
  pour_bottle? do
    satisfy { OS.mac? || Formula["glibc"].installed? || OS::Linux::Glibc.system_version >= "2.18" }
    reason "Requires glibc 2.18 or later. Run brew install glibc"
  end
```
```ruby
  pour_bottle? do
    satisfy { OS.mac? || DevelopmentTools.non_apple_gcc_version("gcc") >= "5" }
    reason "Requires gcc 5 or later. Run brew install gcc"
  end
```

**Comment by jonchang** [comment]
Traveling right now so won’t be able to do much but this looks OK per your research into this problem on slack. Worst case scenario users have to build from source?

**Comment by maxim-belkin** [comment]
Looks good for pouring bottles. A few questions:

1. Why do we set `glibc 2.17` as the minimum version of glibc for bottles? We need to document this better.
1. Do we need `rescue FormulaUnavailableError` to simplify the Homebrew/Linuxbrew merger down the road?
1. What work has to be done to support the solution using the `depends_on` clause in formulae?
    ```
    depends_on :glibc  => "2.18"
    ```
1. Thinking ahead: we could have versioned `glibc` formulae. If a hypothetical formula `X` depends on `glibc@2.23` and that `glibc@2.23` is installed, the proposed code would not be satisfied.

**Comment by sjackman** [comment]
```
strings /gsc/btl/linuxbrew/lib/libstdc++.so.6 | grep -i glibc_ | sort -V
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.14
GLIBC_2.17
GLIBC_2.18
$ fastp --version
fastp: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /projects/btl_scratch/sjackman/brew/lib/libstdc++.so.6)
```
Brewed `gcc` requires `glibc` 2.18 or later. =/

**Comment by sjackman** [comment]
You can pour the brewed `gcc` and then use it to compile and install `glibc`. That appears to work on any system with `glibc` 2.14 or newer.

**Comment by sjackman** [comment]
Here's another take on the same theme that allows pouring `gcc` before compiling `glibc`, possibly with the newly-poured `gcc`.
```ruby
    # Installing bottles on Linux require a recent version of glibc and gcc.
    # GCC is required for libgcc_s.so and libstdc++.so. It depends on glibc.
    begin
      gcc = Formula["gcc"]
      if DevelopmentTools.non_apple_gcc_version("gcc") < gcc.version
        deps += Dependency.expand(gcc) << Dependency.new("gcc")
      end

      glibc = Formula["glibc"]
      if !glibc.installed? && OS::Linux::Glibc.system_version < glibc.version
        deps += Dependency.expand(glibc) << Dependency.new("glibc")
      end
    rescue FormulaUnavailableError
      nil
    end
```

**Comment by sjackman** [comment]
Since this PR does no good for CentOS 7, which was my primary hope, I'm closing this PR without merging. It could maybe be rescued in some other form.

**Comment by sjackman** [comment]
To summarize, `gcc` requires `glibc` 2.14 or newer, and `g++` requires `glibc` 2.18 or newer.

**Comment by maxim-belkin** [comment]
Should we create `glibc@2.14`? :)

**Pull request closed without merging**
