### PR TITLE
shims/linux/super/make: use command -v

### PR DESCRIPTION
**Pull request by maxim-belkin**
... instead of `which`

### CODE REVIEW

**Review by sjackman — CHANGES_REQUESTED** [review]
Please also delete the final blank line at line 26, to make this file identical to upstream. Thanks, Maxim!

**Comment by maxim-belkin** [comment]
Hm... I added new line at the end of the file on purpose, see https://stackoverflow.com/a/37684763

**Comment by sjackman** [comment]
That article is referring to a new line character at the end of the file, not a blank line, which is to consecutive new lines. Run `xxd shims/linux/super/make` and you'll see that your file has two new line characters at the end, where only one is needed.

**Comment by maxim-belkin** [comment]
nice! I haven't ever used `xxd`!

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Good to merge once CI is 🍏. Thanks, Maxim!

**Pull request merged**
