### PR TITLE
core: Create a Gawk requirement.

### PR DESCRIPTION
**Pull request by DoomHammer**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [X] Have you successfully run `brew tests` with your changes locally?

---

In response to #27

### CODE REVIEW

**Comment by sjackman** [comment]
Original issue over here: Original issue over here: https://github.com/Linuxbrew/linuxbrew/issues/953

**Comment by sjackman** [comment]
Even CentOS 5, the oldest distro that I know of supported by Linuxbrew, satisfies the version requirement of gawk (it has 3.1.5), so I feel that doing the version check is overkill. The code can be simplified to a few lines by removing the version check, and simplifies the tests as well.

``` ruby
class GawkRequirement < Requirement
  fatal true
  default_formula "gawk"
  satisfy { which("gawk") }
end
```

`glibc` is the only package that will use this requirement due to the bootstrapping issue—others can simply `depend_on "gawk"`—so I'd suggest moving this requirement into the `glibc` formula itself.

**Comment by DoomHammer** [comment]
As you wish!

**Comment by DoomHammer** [comment]
New approach at https://github.com/Linuxbrew/homebrew-core/pull/231

**Comment by sjackman** [comment]
Thanks, Piotr.

**Pull request closed without merging**
