### PR TITLE
Merge a985f0a5

### PR DESCRIPTION
**Pull request by jonchang**
Conflicts:
      Library/Homebrew/cmd/update-report.rb
      Library/Homebrew/dev-cmd/man.rb
      Library/Homebrew/formula_installer.rb
      Library/Homebrew/manpages/brew.1.md.erb
      Library/Homebrew/test/cleanup_spec.rb
      README.md
      docs/Manpage.md
      manpages/brew.1

### CODE REVIEW

**Comment by iMichka** [comment]
I triggered a new CI build on Travis, it failed due some timeouts downloading dependencies.

**Comment by sjackman** [comment]
The purpose of this merge PR is to pull in upstream PR https://github.com/Homebrew/brew/pull/4659: Always fetch at least the latest tag.

**Comment by sjackman** [comment]
Upstream PR https://github.com/Homebrew/brew/pull/4658 `Set `initial_version` to `nil` when `git describe` fails.` is also useful, and is a better fix for my PR https://github.com/Linuxbrew/brew/pull/779 `update-report: Work around an unusual error`

**Review by iMichka — APPROVED** [review]

**Review by sjackman — APPROVED** [review]

**Comment by jonchang** [comment]
Merged. Thanks all!

**Comment by iMichka** [comment]
Thanks for the merge!

**Pull request merged**
