### PR TITLE
Merge brew 1.3.1

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Review by jonchang — APPROVED** [review]
👍 assuming tests passed

**Comment by bw-yuhogg** [comment]
They passed on Linux. I still haven't been able to fix the Mac tests yet, but we're closer than before.

**Comment by sjackman** [comment]
I usually do the following sanity check when merging `brew`. Assuming it passes, 👍
```sh
brew install hello
brew test hello
brew remove hello
brew install -s hello
brew test hello
```

**Review by sjackman — APPROVED** [review]

**Comment by iMichka** [comment]
Merged. Let's wait 2 days until we tag this.

**Comment by sjackman** [comment]
Thanks, Michka!

**Comment by sjackman** [comment]
> iMichka deployed to github-pages 3 hours ago [View deployment](http://linuxbrew.sh/brew/)

I haven't seen this before. Is that automatic, or did you trigger it? It deployed to http://linuxbrew.sh/brew/ with a few problems. It'd be great to figure out how to fix those small issues and deploy to http://linuxbrew.sh

**Comment by iMichka** [comment]
Nope, I did nothing special. I think it is automatic

**Pull request merged**
