### PR TITLE
Unshallow repository before pulling

### PR DESCRIPTION
**Pull request by maxim-belkin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Supposed to fix a failure observed in #624 when `git pull --ff-only` fails because repository is shallow.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
...not sure whether "bug" is the right label for this PR...

**Comment by sjackman** [comment]
I'm not sure why, but the Docker image `linuxbrew/linuxbrew:latest` is pointing to `linuxbrew/linuxbrew:1.5.13` for some reason. It should be pointing to `master`. I've triggered a rebuild of the Docker image. See if that helps.
https://hub.docker.com/r/linuxbrew/linuxbrew/builds/

**Comment by sjackman** [comment]
Oh, wait. I bet I know what's going on. `brew tap homebrew/core` is causing it to revert to most recent tagged stable version. This issue should be resolved by PR https://github.com/Linuxbrew/brew/pull/678.

**Comment by sjackman** [comment]
This issue should be resolved now. Closing without merging.

**Pull request closed without merging**
