### PR TITLE
Merge 1.7.3

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Failed examples:
rspec ./test/bash_spec.rb:25 # Bash every `.sh` file has valid bash syntax
```
https://circleci.com/gh/Linuxbrew/brew/1222

This test failure is intermittent. Rerunning the job should make it go away.

Otherwise there's a few `brew style` failures and `brew man --fail-if-changed`.

**Comment by iMichka** [comment]
@sjackman I fixed the style errors, and also fixed the "who are you" section.

We should think about how this section will look like once brew is merged upstream.

I already removed one line to simplify things:
> Linuxbrew/homebrew-core's other current maintainers are Shaun Jackman.

I felt that as you already were defined as:
> Linuxbrew's lead maintainer is Shaun Jackman.

it was enough :)

Other changes we could make:
`Bob W. Hogg` could go into the general homebrew former maintainers.

Any other changes? We can also postpone these changes for later, so I can get 1.7.3 out.

**Comment by sjackman** [comment]
The version number output by the program hasn't changed. It still reports 25.6.
```
❯❯❯ curl -LO https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/mac.tbl2asn.gz
❯❯❯ gunzip mac.tbl2asn.gz
❯❯❯ ./mac.tbl2asn - | head -n2
tbl2asn 25.6   arguments:
```

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Looks good to me. Thanks, Michka!

**Pull request merged**
