### PR TITLE
Merge 1.6.3

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Review by iMichka — APPROVED** [review]
Ci is green, good to go :)

**Comment by sjackman** [comment]
TravisCI is failing on both Linux and macOS. It looks as though perhaps gems are not being installed correctly.
```
==> brew audit testbottest --online
Error: No such file or directory - rubocop
==> FAILED
```
https://travis-ci.org/Linuxbrew/brew/jobs/374573738#L345
https://travis-ci.org/Linuxbrew/brew/jobs/374573739#L706

**Comment by sjackman** [comment]
I don't have the time at the moment to debug the TravisCI failure. Merging despite the TravisCI failure.

**Comment by xu-cheng** [comment]
So the ARM portable ruby is removed?

**Comment by sjackman** [comment]
PR https://github.com/Homebrew/brew/pull/4149 adds it back.

**Pull request merged**
