### PR TITLE
Tell people using Linuxbrew/brew to switch to Homebrew/brew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by scpeters** [comment]
I take it the linuxbrew install script will continue to be maintained?

* `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`

**Comment by iMichka** [comment]
> I take it the linuxbrew install script will continue to be maintained?

I would like to see if we can upstream it and have a common install script.

Homebrew announced that there was beta Linux support, and I am worried that some people may just read https://brew.sh and run the mac script. Another solution is to have both scripts but to update the doc and provide both links.

**Comment by scpeters** [comment]
Currently the brew installer directs to the linuxbrew page if linux is detected

https://github.com/Homebrew/install/blob/master/install#L157-L161

As long as `Linuxbrew/homebrew-core` is separate, I think there should be a separate linuxbrew.sh page, but I suppose upstreaming the installer could be considered.

**Comment by sjackman** [comment]
I've opened a PR to add `install.sh` to Homebrew/install: https://github.com/Homebrew/install/pull/174
If this PR is merged,
```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```
will work on both macOS and Linux.

**Comment by scpeters** [comment]
@sjackman nice, I like that approach

**Comment by sjackman** [comment]
Merged.

**Pull request merged**
