### PR TITLE
clang: Gate the use of libc++ to Mac

### PR DESCRIPTION
**Pull request by theopolis**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

---

### CODE REVIEW

**Comment by theopolis** [comment]
`libc++` provides the system C++ implementation for Darwin platforms, based on LLVM. For most Linux systems the C++ implementation is provided by GCC. When folks override their compiler to `clang` it should default to GCC for C++.

**Comment by bw-yuhogg** [comment]
Agree with this change (not tested yet).

According to LLVM's documentation, Linux is not fully supported by libc++ yet anyways. The [most recent results](http://libcxx.llvm.org/results.Linux.html) show 33 failures.

@theopolis, thanks for contributing :smile:

**Comment by theopolis** [comment]
Now realizing I used the GCC library name in the commit and PR title. Please excuse me :P 

I wasn't able to run `brew test` locally due to some odd permission bits I need to investigate-- but I've tried setting `clang` as my compiler and installing various packages and everything seems good to go!

**Comment by bw-yuhogg** [comment]
> I wasn't able to run brew test locally due to some odd permission bits I need to investigate

Try `umask 022` before running the tests. That happens to me a lot too.

**Comment by theopolis** [comment]
For some context on why I'm playing with clang:

On some distributions there's a GCC 5.1+ installed so my brew-installed libraries have the `cxx11` ABI version injected into the relative symbols. If a Formula explicitly sets `clang` then there might be trouble. It's nice to have the `--cc=clang` option around for these odd-ball scenarios. :dancer:

**Comment by theopolis** [comment]
> Try umask 022 before running the tests. That happens to me a lot too.

Epic, thanks @rwhogg!

**Comment by sjackman** [comment]
Makes sense to me, but I haven't used `clang` on Linux. Does it work equally well with `libstdc++` on Linux? I guess from what you're saying, Bob, it works better with `libstdc++` than `libc++` on Linux.

@DoomHammer Any comments on this patch, Piotr?

**Comment by theopolis** [comment]
On Linux:

`libstdc++` = 👍 
`libc++` = 👎

**Comment by sjackman** [comment]
:smile: ✅

**Comment by sjackman** [comment]
Once Piotr has responded, I'm happy with merging this PR.

**Comment by DoomHammer** [comment]
Hello, missed that one, sorry.

My experiences (somehow limited, mind you) are that `libc++` on Linux rather can't, so this patch should be good for us.

A bit similar was https://github.com/Linuxbrew/homebrew-core/commit/c44e038cd7ff2fdda467a4c8cbaf13834f75247f

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Teddy!

**Pull request closed without merging**
