### PR TITLE
Merge 1.3.2

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Failures:

  1) Utils#self.svn_available? returns svn version if svn available
     Failure/Error: expect(described_class.svn_available?).to be_truthy

       expected: truthy value
            got: false
     # ./test/utils/svn_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

```
Failures:

  1) Utils::Analytics::os_prefix_ci when anonymous_os_prefix_ci is not set returns OS_VERSION and prefix when HOMEBREW_PREFIX is not /usr/local
     Failure/Error: expect(described_class.os_prefix_ci).to include("#{OS_VERSION}, non-/usr/local")
       expected "4.4.0-92-generic, custom-prefix, CI" to include "4.4.0-92-generic, non-/usr/local"
     # ./test/utils/analytics_spec.rb:13:in `block (4 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

https://circleci.com/gh/Linuxbrew/brew/615

**Comment by sjackman** [comment]
I added commit 3ec4d25b23b67a80f398e2f031330f63fafd0536 to this PR to fix `test/utils/analytics_spec.rb:13`.

**Comment by sjackman** [comment]
I've added commit ff128904a5ffe05c91585d4917acdaa909b1155c to this PR to hopefully fix `test/utils/svn_spec.rb:10`.

**Comment by sjackman** [comment]
PR #484 was merged in the mean time. So we'll need to redo this merge. That being the case, I'm going to merge PR #489 now.

**Comment by sjackman** [comment]
I've fixed the two `brew tests` failures on CircleCI. There's another 18 failures on TravisCI. Yipes.
https://travis-ci.org/Linuxbrew/brew/jobs/279792369#L1226

**Comment by sjackman** [comment]
Strange `brew tests` failure on TravisCI but not CircleCI. I can't reproduce this error locally.
```
  1) brew home opens the homepage for a given Formula
     Failure/Error:
       expect { brew "home", "testball", "HOMEBREW_BROWSER" => "echo" }
         .to output("#{Formula["testball"].homepage}\n").to_stdout
         .and not_to_output.to_stderr
         .and be_a_success
       expected block to output "\n" to stdout, but output "https://example.com/testball\n"
     # ./test/cmd/home_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/integration_test.rb:44:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
https://travis-ci.org/Linuxbrew/brew/jobs/279792369#L1284

**Comment by iMichka** [comment]
Maybe https://github.com/Homebrew/brew/pull/3127 or https://github.com/Homebrew/brew/issues/3113 ? But not sure how these may be related.

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/brew/pull/497

**Pull request closed without merging**
