### PR TITLE
Merge Homebrew tag 1.2.6

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Review by jonchang — APPROVED** [review]
I don't see any changes that would appreciably alter Linux and if tests pass :+1:

**Comment by iMichka** [comment]
Tests are green. @jonchang @sjackman I would propose to do following:
- push the 1.2.5 tag
- merge this and wait 1-2 days

Is that ok for you?

**Review by bw-yuhogg — APPROVED** [review]
😺

**Comment by iMichka** [comment]
1.2.5 tag pushed and 1.2.6 merged!

**Pull request merged**
