### PR TITLE
README: add Alyssa Ross to maintainers list

### LINKED ISSUE #461: Welcome @alyssais to Linuxbrew
- [x]  Add to Slack
- [x]  Add to the Slack maintainers channel
- [x]  Introduce to existing members
- [x]  Announce at Linuxbrew Updates
- [x]  Add to the GitHub team
- [x]  Add to the Bintray organization
- [x]  Add to Google Analytics if desired
- [x]  Add name to Who Are You? in README.md https://github.com/Linuxbrew/brew/pull/463

https://github.com/Linuxbrew/brew/wiki/New-Maintainer

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Closes #461.

### CODE REVIEW

**Review by sjackman — APPROVED** [review]
Welcome, Alyssa!

**Review by maxim-belkin — APPROVED** [review]

**Comment by sjackman** [comment]
@alyssais Feel free to merge this PR whenever you like with the GitHub `Squash and merge` button.

**Comment by sjackman** [comment]
`brew man --fail-if-changed` is failing. Does updating the `README.md` cause this test to fail?
```sh
brew pull https://github.com/Linuxbrew/brew/pull/463
linuxbrew man --fail-if-changed
echo $?
1
```
Yes, yes it does.

@alyssais Please run `linuxbrew man` and commit the changes to `docs/Manpage.md` and `manpages/brew.1` to this PR.

**Comment by sjackman** [comment]
Good timing! This'll make it into the release of Linuxbrew 1.3.0 planned for Monday.

**Pull request merged**
