### PR TITLE
Merge homebrew@a11039d8

### PR DESCRIPTION
**Pull request by jonchang**
Conflicts:
          Library/Homebrew/formula_cellar_checks.rb
          Library/Homebrew/formula_support.rb
          Library/Homebrew/test/spec_helper.rb
          README.md
          docs/Manpage.md
          manpages/brew.1

### CODE REVIEW

**Comment by jonchang** [comment]
Test failed due to the svn tests picking up the shim. Attempting a different way to detect the workability of this.

**Comment by jonchang** [comment]
Travis failure seems to be unrelated.

**Comment by maxim-belkin** [comment]
> Travis failure seems to be unrelated.

I tend to agree

**Comment by sjackman** [comment]
You can decorate a test that requires `svn` with `:needs_svn`.

https://github.com/Linuxbrew/brew/blob/00889148875a5d787ff59fe1e371e7b42efaa832/Library/Homebrew/test/utils/svn_spec.rb#L33

https://github.com/Linuxbrew/brew/blob/adbfac257ec8617651b67a2385673a740294b78e/Library/Homebrew/test/spec_helper.rb#L87-L89

**Comment by sjackman** [comment]
Is this merge intended to pick up any particular upstream PR?

**Comment by sjackman** [comment]
Previously the `svn` test was…
```ruby
skip "Requires subversion." unless File.executable? "/usr/bin/svn"
```
https://github.com/Linuxbrew/brew/pull/814/files#diff-6f522f1344e6482f5935d515cddbbc66L88
and now
```ruby
skip "subversion not installed." unless system which("svn"), "--help"
```
I have a slight preference for the former, because testing for file existence is faster than executing a program.

**Comment by maxim-belkin** [comment]
how about `unless which("svn")` ?

**Comment by sjackman** [comment]
That doesn't work unfortunately because it picks up the shim in `shims/scm/svn` whether SVN is installed or not. Three ways to test whether SVN are installed are…
```sh
test -x /usr/bin/svn
shims/scm/svn --homebrew=print-path
shims/scm/svn --version
```

**Comment by jonchang** [comment]
I’d want it to work equally well on macOS and Linux though, hence actually running the thing and seeing if it errors out. 

I’m looking for stuff to upstream and that’s easier when the linuxbrew master is up to date.

**Comment by maxim-belkin** [comment]
`/usr/bin/svn` excludes other possible paths from consideration (like `/opt`).
The other two fail for me

**Comment by sjackman** [comment]
> I’d want it to work equally well on macOS and Linux though, hence actually running the thing and seeing if it errors out.

`File.executable? "/usr/bin/svn"` should work equally well on Linux and macOS. That file exists on macOS, and TravisCI, and does not exist on CircleCI.

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/brew/pull/817

**Pull request closed without merging**
