### PR TITLE
Install bzip2 if required to decompress bz2 files

### PR DESCRIPTION
**Pull request by alyssais**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Without this, `brew install ncurses` fails on a fresh Ubuntu docker image because it tries to download a .bz2 file it can't decompress.

### CODE REVIEW

**Review by bw-yuhogg — APPROVED** [review]
Thanks @alyssais!

**Review by sjackman — APPROVED** [review]
Thanks, Alyssa!

**Comment by sjackman** [comment]
Please tack `for Linuxbrew` on to the end of all commit log messages for Linuxbrew. It makes it easier to grep through `git log --oneline` for Linuxbrew changes. It's okay if `for Linuxbrew` exceeds the 50 character limit, if the rest of the message fits within it.

**Comment by sjackman** [comment]
I've considered abbreviating that to simply `[Linux]` if we think that `for Linuxbrew` is too verbose.

**Comment by bw-yuhogg** [comment]
> I've considered abbreviating that to simply [Linux] if we think that for Linuxbrew is too verbose.

👍, both because it's shorter and because it means we don't get mixed up on the capitalization of "for" vs. "For".

**Comment by alyssais** [comment]
What's up with Travis?

**Comment by sjackman** [comment]
TravisCI works on Linux but is not currently happy on macOS. To address this issue, Homebrew/test-bot needs to be merged into Linuxbrew/test-bot. Bob @rwhogg started such a merge here: https://github.com/Linuxbrew/homebrew-test-bot/pull/24
```
Error: No such file or directory - /Users/travis/build/Linuxbrew/brew/Library/Homebrew/test/support/fixtures/testbottest.rb
```
https://travis-ci.org/Linuxbrew/brew/jobs/265636477#L136

**Comment by sjackman** [comment]
Merged. Thanks, Alyssa!

**Pull request merged**
