### PR TITLE
Add Michka Popoff to the maintainers list

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

### CODE REVIEW

**Review by bw-yuhogg — APPROVED** [review]

**Comment by iMichka** [comment]
Seems I can't merge this directly, as the master branch is protected. What is the procedure to merge this? :)

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Is it the case that you can't merge it because the TravisCI test is failing on macOS?

**Comment by sjackman** [comment]
I believe you should be able to merge this PR using the GitHub web interface. Select `Squash and merge`.

**Comment by sjackman** [comment]
I'd be ever grateful if someone had time to fix the TravisCI macOS failure. 🤗

**Pull request merged**
