### PR TITLE
Revert "Dockerfile: install unzip and subversion too"

### PR DESCRIPTION
**Pull request by sjackman**
This reverts commit f111c20805584eea65bc82a594103d9917ed2292.

### CODE REVIEW

**Comment by sjackman** [comment]
CI was successful, so merging.

**Comment by iMichka** [comment]
Weird. Maybe upstream updated the tests.

**Comment by sjackman** [comment]
No, the latest Docker Hub build failed.
https://hub.docker.com/r/linuxbrew/linuxbrew/builds/
These tests were run in the previous `linuxbrew/linuxbrew` Docker image that had `svn` and `unzip` installed, which is why CI succeeded. I'll fix the tests.

**Comment by iMichka** [comment]
The conclusion we came to is that you can not fix the tests. Because before the tests are run, all brew packages are uninstalled (including unzip and svn). So you need system unzip and svn.

**Comment by sjackman** [comment]
In other cases, I've skipped the tests that require system tools, like svn and unzip, if they're not available.

**Pull request merged**
