### PR TITLE
unpack_strategy: jar lua_rock zip require zipinfo [Linux]

### PR DESCRIPTION
**Pull request by sjackman**
Fix `Error: No such file or directory - zipinfo`

### CODE REVIEW

**Comment by sjackman** [comment]
Although I see `Error: No such file or directory - zipinfo` with 468d869022ebe725d7b7745adfa872db3e6c16c9 (tag: 1.7.1), I do not see this error with ebd8333e63d844b7772eac83f28e3a18f3fb3b62.

**Comment by sjackman** [comment]
@reitermarkus Is `UnpackStrategy.dependencies` used by `brew install`?

`brew postinstall pypy` fails on Linuxbrew when `unzip` is not available, because it attempts to download and unpack a zip file. Any thoughts on how to fix it?

**Comment by reitermarkus** [comment]
> Is `UnpackStrategy.dependencies` used by `brew install`?

I don't think so. `brew install` only infers dependencies from the extension and from the download strategy, but not the unpack strategy.

**Comment by reitermarkus** [comment]
To fix `brew postinstall pypy`, you would have to install dependencies on-demand somewhere between downloading and unpacking.

**Comment by sjackman** [comment]
Thanks for the info, Markus. I'm closing out this PR for now, unresolved.

**Pull request closed without merging**
