### PR TITLE
Merge brew 1.3.2

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
I see this error on TravisCI, but not on CircleCI, and I can't reproduce it locally.
```
==> brew tests --no-compat

  1) brew home opens the homepage for a given Formula
     Failure/Error:
       expect { brew "home", "testball", "HOMEBREW_BROWSER" => "echo" }
         .to output("#{Formula["testball"].homepage}\n").to_stdout
         .and not_to_output.to_stderr
         .and be_a_success
       expected block to output "\n" to stdout, but output "https://example.com/testball\n"
     # ./test/cmd/home_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/integration_test.rb:44:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
https://travis-ci.org/Linuxbrew/brew/jobs/285741838#L1284

**Comment by sjackman** [comment]
```
  1) Tap #issues_url
     Failure/Error: expect(t.issues_url).to eq("https://github.com/someone/homebrew-foo/issues")
       expected: "https://github.com/someone/homebrew-foo/issues"
            got: nil
       (compared using ==)
     # ./test/tap_spec.rb:109:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
https://travis-ci.org/Linuxbrew/brew/jobs/285751911#L1237

**Comment by sjackman** [comment]
```
  3) Tap #install and #uninstall
     Failure/Error: tap.install clone_target: subject.path/".git"
     RuntimeError:
       Git is unavailable
     # ./utils/git.rb:58:in `rescue in ensure_git_installed!'
     # ./utils/git.rb:54:in `ensure_git_installed!'
     # ./tap.rb:250:in `install'
     # ./test/tap_spec.rb:238:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:96:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
https://travis-ci.org/Linuxbrew/brew/jobs/285751911#L1259

18 similar failures.

**Comment by iMichka** [comment]
Did you try with `testballhome` instead of `testball`?

**Comment by sjackman** [comment]
I've applied a hack work around to resolve `brew home opens the homepage for a given Formula`  aa9cad9d698ba497b364224c03bed7e70d4a5af1

**Comment by sjackman** [comment]
I've cherrypicked a37c7572b1d344230ca138a488004b151ffbfaf0 `utils/git: cache less aggressively.` to resolve the `git` errors.

**Comment by sjackman** [comment]
Found the fix to the `test/cmd/home` failure! Thanks, Michka!
https://github.com/Homebrew/brew/commit/49d2d7b94d85dd150956ea14d66a34870d2f70fd

**Comment by sjackman** [comment]
Merged! ✨

**Pull request merged**
