### PR TITLE
update-report: Remove --local option [Linux]

### PR DESCRIPTION
**Pull request by sjackman**
Older versions of git do not support this option.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks for the fixing.

Any chance to turn the `safe_system` to `system`. I don’t think a failure of the analysis/donations notice should prevent the rest of update procedures to be executed.

**Comment by sjackman** [comment]
I prefer `safe_system` unless there's a particular failure mechanism that we expect and want to avoid. I'd prefer to hear about unexpected failures.

**Comment by xu-cheng** [comment]
We could output warnings for the failures. The thing is that these `safe_system` may prevent more important codes to be executed such as homebrew core migration (functions like `*_if_necessary`), tap migration, etc.

**Comment by sjackman** [comment]
You may if you like open a PR implementing this suggestion at Homebrew/brew. Linuxbrew/brew is currently being merged into Homebrew/brew, so I'm avoiding accepting PRs directly into Linuxbrew/brew that may not be accepted upstream at Homebrew/brew.

**Pull request merged**
