### PR TITLE
Merge Homebrew tag 1.2.5

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by jonchang** [comment]
While resolving merge conflicts, I noted that https://github.com/Linuxbrew/brew/pull/143 may be a good candidate for upstreaming.

**Comment by jonchang** [comment]
Is the Travis CI macOS failure expected? I notice that for 1.2.4 and 1.2.3 they were also failing.

**Comment by bw-yuhogg** [comment]
> Is the Travis CI macOS failure expected? I notice that for 1.2.4 and 1.2.3 they were also failing.

They've been failing for a while, and we would appreciate if someone had the time to look into them, but yeah, it's a known issue ☹️

**Comment by sjackman** [comment]
Thanks for the PR, Jon! Is 1.2.5 ready to merge?

**Comment by sjackman** [comment]
> While resolving merge conflicts, I noted that #143 may be a good candidate for upstreaming.

I agree. Would you like to submit a PR upstream?

**Comment by jonchang** [comment]
Yeah I think this is ready to merge.

**Comment by sjackman** [comment]
Merged. Thanks, Jon!

**Comment by bw-yuhogg** [comment]
> They've been failing for a while, and we would appreciate if someone had the time to look into them, but yeah, it's a known issue ☹️

I think I've figured out why the macOS builds are failing. Mike deleted the file `Library/Homebrew/test/support/fixtures/testbottest.rb` in https://github.com/Homebrew/brew/pull/2686, which is the file Travis is complaining about (see https://travis-ci.org/Linuxbrew/brew/jobs/258957116#L131).

That file can now be found in the test-bot repo, so I think all we have to do is merge homebrew/test-bot into linuxbrew/test-bot and it'll start working again.

**Pull request merged**
