### PR TITLE
README.md: Remove the Ruby dependency for Linuxbrew

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Review by rhoggSugarcrm — APPROVED** [review]

**Review by bw-yuhogg — APPROVED** [review]
Thanks Shaun!

**Comment by sjackman** [comment]
```
==> brew man --fail-if-changed
Error: undefined method `gsub' for nil:NilClass
/home/travis/build/Linuxbrew/brew/Library/Homebrew/dev-cmd/man.rb:67:in `build_man_page'
/home/travis/build/Linuxbrew/brew/Library/Homebrew/dev-cmd/man.rb:40:in `regenerate_man_pages'
/home/travis/build/Linuxbrew/brew/Library/Homebrew/dev-cmd/man.rb:28:in `man'
/home/travis/build/Linuxbrew/brew/Library/Homebrew/brew.rb:93:in `<main>'
==> FAILED
```
https://travis-ci.org/Linuxbrew/brew/jobs/257058038#L364

Grrr. Likely an unrelated error. Merging anyway.

**Comment by bw-yuhogg** [comment]
> Grrr. Likely an unrelated error. Merging anyway.

Yeah, it's unrelated. The reason is that `brew man` includes code to extract the "Who Are You" section from README.md. This has been failing ever since I merged #428, because the sections it's parsing don't exist anymore.

**Comment by bw-yuhogg** [comment]
I've opened #439 to fix the problem with `brew man`.

**Pull request merged**
