### PR TITLE
Update brew 1.5.1

### PR DESCRIPTION
**Pull request by drbenmorgan**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Fixes supernemo-dbd/homebrew-cadfael#43

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Sorry, bad mistake in the PR submission...

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan - looks like it is working fine now.

**Comment by sjackman** [comment]
No worries, Ben. I'm curious, what feature(s) are missing from Linuxbrew/brew preventing you from using stock Linuxbrew?
I've started a new GitHub organization Brewsci to house science taps: https://github.com/Brewsci/
I maintain the tap Brewsci/bio: https://github.com/brewsci/homebrew-bio
and monitor the retired Brewsci/science tap: https://github.com/brewsci/homebrew-science

**Comment by drbenmorgan** [comment]
@sjackman Thanks, and apologies again...

Using a fork is largely an artefact of history/inertia at this point, plus a backlog on my part to implement and automate Linux/macOS bottle building for our tap... 

Thanks for the pointer to Brewsci, the discussion in brewsci/homebrew-science#10 is very interesting! There might be some interest in a tap here for High Energy Physics (there's already davidchall/homebrew-hep of course), especially as there's quite a bit of [interest/work in packaging in the community](http://hepsoftwarefoundation.org/activities/packaging.html). 

Thanks for all your great work on Linuxbrew - been an incredible help to me and the projects I work on!

**Comment by sjackman** [comment]
Glad to hear it! Thanks for the positive feedback. Let me know if you'd like to start a Brewsci/physics tap, and I can can help get you set up with automated bottling on CircleCI.

**Pull request closed without merging**
