### PR TITLE
Merge 1.7.1

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/config.rb:40:in `<top (required)>': uninitialized constant OS (NameError)
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:14:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:15:in `require_relative'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:15:in `<main>'

**Comment by jonchang** [comment]
Looks like config.rb needs to `require "os"` in order to get `OS.mac?`

**Comment by jonchang** [comment]
Actually, that's weird, because `global.rb` should provide `OS` for everything. https://github.com/Homebrew/brew/pull/4500 seems to be the culprit, because `config` is included before `os` in `global.rb`

**Comment by iMichka** [comment]
```
An error occurred while loading ./test/system_command_spec.rb.
Failure/Error:
  describe SystemCommand do
    describe "#initialize" do
      let(:env_args) { ["bash", "-c", 'printf "%s" "${A?}" "${B?}" "${C?}"'] }
  
      context "when given some environment variables" do
        subject {
          described_class.new(
            "env",
            args: env_args,
            env: { "A" => "1", "B" => "2", "C" => "3" },

NameError:
  uninitialized constant SystemCommand
# ./test/system_command_spec.rb:1:in `<top (required)>'
```

**Comment by iMichka** [comment]
It is weird that `system_command_result_spec.rb`as a `require "system_command"`, but not `system_command_spec.rb`.

**Comment by iMichka** [comment]
Merged. I will build some bottles with this and tag it later. I need 1.7.1 to push the make shim fix to our users.

**Pull request merged**
